# Generated by Django 3.2 on 2023-01-15 20:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profilemodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100, verbose_name='Name')),
                ('Family', models.CharField(max_length=100, verbose_name='Family')),
                ('Gender', models.IntegerField(choices=[('Man', 'Man'), ('Woman', 'Woman')], verbose_name='Gender')),
                ('Profile_image', models.ImageField(upload_to='profile_images/', verbose_name='picture')),
                ('Credit', models.IntegerField(default=0, verbose_name='credit')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'PROFILE',
                'verbose_name_plural': 'PROFILE',
            },
        ),
    ]
