# Generated by Django 3.2 on 2023-01-09 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketsales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='concertmodel',
            name='test',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
