# Generated by Django 3.2 on 2023-01-10 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticketsales', '0003_auto_20230109_2300'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='concertmodel',
            options={'verbose_name': 'CONCERT', 'verbose_name_plural': 'CONCERT'},
        ),
        migrations.AlterModelOptions(
            name='locationmodel',
            options={'verbose_name': 'LOCATION', 'verbose_name_plural': 'LOCATION'},
        ),
        migrations.AlterModelOptions(
            name='profilemodel',
            options={'verbose_name': 'PROFILE', 'verbose_name_plural': 'PROFILE'},
        ),
        migrations.AlterModelOptions(
            name='ticketmodel',
            options={'verbose_name': 'TICKET', 'verbose_name_plural': 'TICKET'},
        ),
        migrations.AlterModelOptions(
            name='timemodel',
            options={'verbose_name': 'TIME', 'verbose_name_plural': 'TIME'},
        ),
        migrations.AlterField(
            model_name='concertmodel',
            name='Length',
            field=models.IntegerField(verbose_name='concert name'),
        ),
        migrations.AlterField(
            model_name='concertmodel',
            name='Name',
            field=models.CharField(max_length=100, verbose_name='concert name'),
        ),
        migrations.AlterField(
            model_name='concertmodel',
            name='Poster',
            field=models.ImageField(null=True, upload_to='concert_image/', verbose_name='poster'),
        ),
        migrations.AlterField(
            model_name='concertmodel',
            name='SingerName',
            field=models.CharField(max_length=100, verbose_name='singer name'),
        ),
        migrations.AlterField(
            model_name='locationmodel',
            name='Address',
            field=models.CharField(default='Amsterdam, ...', max_length=500, verbose_name='address'),
        ),
        migrations.AlterField(
            model_name='locationmodel',
            name='Capacity',
            field=models.IntegerField(verbose_name='capacity'),
        ),
        migrations.AlterField(
            model_name='locationmodel',
            name='Name',
            field=models.CharField(max_length=100, verbose_name='location name'),
        ),
        migrations.AlterField(
            model_name='locationmodel',
            name='Phone',
            field=models.CharField(max_length=11, null=True, verbose_name='phone'),
        ),
        migrations.AlterField(
            model_name='locationmodel',
            name='idNumber',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='location code'),
        ),
        migrations.AlterField(
            model_name='profilemodel',
            name='Family',
            field=models.CharField(max_length=100, verbose_name='Family'),
        ),
        migrations.AlterField(
            model_name='profilemodel',
            name='Gender',
            field=models.IntegerField(choices=[('Man', 'Man'), ('Woman', 'Woman')], verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='profilemodel',
            name='Name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='profilemodel',
            name='Profile_image',
            field=models.ImageField(upload_to='profile_images/', verbose_name='picture'),
        ),
        migrations.AlterField(
            model_name='ticketmodel',
            name='Name',
            field=models.CharField(max_length=100, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='ticketmodel',
            name='Price',
            field=models.IntegerField(verbose_name='price'),
        ),
        migrations.AlterField(
            model_name='ticketmodel',
            name='Profilemodel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ticketsales.profilemodel', verbose_name='user'),
        ),
        migrations.AlterField(
            model_name='ticketmodel',
            name='Ticket_image',
            field=models.ImageField(upload_to='ticket_images/', verbose_name='picture'),
        ),
        migrations.AlterField(
            model_name='ticketmodel',
            name='Timemodel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ticketsales.timemodel', verbose_name='session'),
        ),
        migrations.AlterField(
            model_name='timemodel',
            name='Concertmodel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ticketsales.concertmodel', verbose_name='concert name'),
        ),
        migrations.AlterField(
            model_name='timemodel',
            name='Locationmodel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ticketsales.locationmodel', verbose_name='location'),
        ),
        migrations.AlterField(
            model_name='timemodel',
            name='Status',
            field=models.IntegerField(choices=[('Start', 'ticket sale is started for this session'), ('End', 'ticket sale is over'), ('Cancel', 'this session is canceled'), ('Sale', 'ticket is still being sold')], verbose_name='status'),
        ),
    ]
