# Generated by Django 3.2 on 2023-01-10 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketsales', '0004_auto_20230110_1730'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='concertmodel',
            name='test',
        ),
        migrations.AlterField(
            model_name='timemodel',
            name='Seats',
            field=models.IntegerField(verbose_name='no of seats'),
        ),
        migrations.AlterField(
            model_name='timemodel',
            name='StartDateTime',
            field=models.DateTimeField(verbose_name='concert date'),
        ),
    ]
